INSERT INTO tipodocumento
	(tipo, sigla)
	VALUES('Cedula de Ciudadanía','CC'),
		('Registro Civil','RC'),
		('Tarjeta de Identidad','TI'),
		('Cedula de Extranjeria','CE'),
		('Pasaporte','PS');

INSERT INTO pais
	(id, nombre)
	VALUES (1, 'Colombia'),
		(2, 'Venezuela'),
		(3, 'Ecuador'),
		(4, 'Perú');

INSERT INTO ciudad
	(nombre, region, idpais)
	VALUES('LETICIA', 'Amazonas', 1),
		('PUERTO NARIÑO', 'Amazonas', 1),
		('ABEJORRAL', 'Antioquia', 1),
		('ABRIAQUI', 'Antioquia', 1),
		('ALEJANDRIA', 'Antioquia', 1),
		('AMAGA', 'Antioquia', 1),
		('AMALFI', 'Antioquia', 1),
		('ANDES', 'Antioquia', 1),
		('ANGELOPOLIS', 'Antioquia', 1),
		('ANGOSTURA', 'Antioquia', 1),
		('ANORI', 'Antioquia', 1),
		('ANZA', 'Antioquia', 1),
		('APARTADO', 'Antioquia', 1),
		('ARBOLETES', 'Antioquia', 1),
		('ARGELIA', 'Antioquia', 1),
		('ARMENIA', 'Antioquia', 1),
		('BARBOSA', 'Antioquia', 1),
		('BELLO', 'Antioquia', 1),
		('BELMIRA', 'Antioquia', 1),
		('BETANIA', 'Antioquia', 1),
		('BETULIA', 'Antioquia', 1),
		('BOLIVAR', 'Antioquia', 1),
		('BRICEÑO', 'Antioquia', 1),
		('BURITICA', 'Antioquia', 1),
		('CACERES', 'Antioquia', 1),
		('CAICEDO', 'Antioquia', 1),
		('CALDAS', 'Antioquia', 1),
		('CAMPAMENTO', 'Antioquia', 1),
		('CAÑASGORDAS', 'Antioquia', 1),
		('CARACOLI', 'Antioquia', 1),
		('CARAMANTA', 'Antioquia', 1),
		('CARMEN DE VIBORAL', 'Antioquia', 1),
		('CAROLINA', 'Antioquia', 1),
		('CAUCASIA', 'Antioquia', 1),
		('CHIGORODO', 'Antioquia', 1),
		('CISNEROS', 'Antioquia', 1),
		('COCORNA', 'Antioquia', 1),
		('CONCEPCION', 'Antioquia', 1),
		('CONCORDIA', 'Antioquia', 1),
		('COPACABANA', 'Antioquia', 1),
		('DABEIBA', 'Antioquia', 1),
		('DON MATIAS', 'Antioquia', 1),
		('EBEJICO', 'Antioquia', 1),
		('EL BAGRE', 'Antioquia', 1),
		('EL JORDAN', 'Antioquia', 1),
		('ENTRERRIOS', 'Antioquia', 1),
		('ENVIGADO', 'Antioquia', 1),
		('FREDONIA', 'Antioquia', 1),
		('FRONTINO', 'Antioquia', 1),
		('GIRALDO', 'Antioquia', 1),
		('GIRARDOTA', 'Antioquia', 1),
		('GOMEZ PLATA', 'Antioquia', 1),
		('GRANADA', 'Antioquia', 1),
		('GUADALUPE', 'Antioquia', 1),
		('GUARNE', 'Antioquia', 1),
		('GUATAPE', 'Antioquia', 1),
		('HELICONIA', 'Antioquia', 1),
		('HISPANIA', 'Antioquia', 1),
		('ITAGÜI', 'Antioquia', 1),
		('ITUANGO', 'Antioquia', 1),
		('JARDIN', 'Antioquia', 1),
		('JERICO', 'Antioquia', 1),
		('LA CEJA', 'Antioquia', 1),
		('LA ESTRELLA', 'Antioquia', 1),
		('LA PINTADA', 'Antioquia', 1),
		('LA UNION', 'Antioquia', 1),
		('LIBORINA', 'Antioquia', 1),
		('MACEO', 'Antioquia', 1),
		('MARINILLA', 'Antioquia', 1),
		('MEDELLIN', 'Antioquia', 1),
		('MONTEBELLO', 'Antioquia', 1),
		('MURINDO', 'Antioquia', 1),
		('MUTATA', 'Antioquia', 1),
		('NARIÑO', 'Antioquia', 1),
		('NECHI', 'Antioquia', 1),
		('NECOCLI', 'Antioquia', 1),
		('OLAYA', 'Antioquia', 1),
		('PEÑOL', 'Antioquia', 1),
		('PEQUE', 'Antioquia', 1),
		('PUEBLO RICO', 'Antioquia', 1),
		('PUERTO BERRIO', 'Antioquia', 1),
		('PUERTO NARE', 'Antioquia', 1),
		('PUERTO TRIUNFO', 'Antioquia', 1),
		('REMEDIOS', 'Antioquia', 1),
		('RETIRO', 'Antioquia', 1),
		('RIONEGRO', 'Antioquia', 1),
		('SABANALARGA', 'Antioquia', 1),
		('SABANETA', 'Antioquia', 1),
		('SALGAR', 'Antioquia', 1),
		('SAN ANDRES', 'Antioquia', 1),
		('SAN CARLOS', 'Antioquia', 1),
		('SAN FRANCISCO', 'Antioquia', 1),
		('SAN JERONIMO', 'Antioquia', 1),
		('SAN JOSE DE LA MONTAÑA', 'Antioquia', 1),
		('SAN JUAN DE URABA', 'Antioquia', 1),
		('SAN LUIS', 'Antioquia', 1),
		('SAN PEDRO', 'Antioquia', 1),
		('SAN PEDRO DE URABA', 'Antioquia', 1),
		('SAN RAFAEL', 'Antioquia', 1),
		('SAN ROQUE', 'Antioquia', 1),
		('SAN VICENTE', 'Antioquia', 1),
		('SANTA BARBARA', 'Antioquia', 1),
		('SANTA FE DE ANTIOQUIA', 'Antioquia', 1),
		('SANTA ROSA DE OSOS', 'Antioquia', 1),
		('SANTIAGO', 'Antioquia', 1),
		('SANTO DOMINGO', 'Antioquia', 1),
		('SANTUARIO', 'Antioquia', 1),
		('SEGOVIA', 'Antioquia', 1),
		('SONSON', 'Antioquia', 1),
		('SOPETRAN', 'Antioquia', 1),
		('TAMESIS', 'Antioquia', 1),
		('TARAZA', 'Antioquia', 1),
		('TARSO', 'Antioquia', 1),
		('TITIRIBI', 'Antioquia', 1),
		('TOLEDO', 'Antioquia', 1),
		('TURBO', 'Antioquia', 1),
		('URAMITA', 'Antioquia', 1),
		('URRAO', 'Antioquia', 1),
		('VALDIVIA', 'Antioquia', 1),
		('VALPARAISO', 'Antioquia', 1),
		('VEGACHI', 'Antioquia', 1),
		('VENECIA', 'Antioquia', 1),
		('VIGIA DEL FUERTE', 'Antioquia', 1),
		('YALI', 'Antioquia', 1),
		('YARUMAL', 'Antioquia', 1),
		('YOLOMBO', 'Antioquia', 1),
		('YONDO', 'Antioquia', 1),
		('ZARAGOZA', 'Antioquia', 1),
		('ARAUCA', 'Arauca', 1),
		('ARAUQUITA', 'Arauca', 1),
		('CRAVO NORTE', 'Arauca', 1),
		('FORTUL', 'Arauca', 1),
		('PUERTO RONDON', 'Arauca', 1),
		('SARAVENA', 'Arauca', 1),
		('TAME', 'Arauca', 1),
		('PROVIDENCIA', 'Archipielago San Andres y Providencia', 1),
		('SAN ANDRES', 'Archipielago San Andres y Providencia', 1),
		('BARANOA', 'Atlantico', 1),
		('BARRANQUILLA', 'Atlantico', 1),
		('CAMPO DE LA CRUZ', 'Atlantico', 1),
		('CANDELARIA', 'Atlantico', 1),
		('GALAPA', 'Atlantico', 1),
		('JUAN DE ACOSTA', 'Atlantico', 1),
		('LUNUACO', 'Atlantico', 1),
		('MALAMBO', 'Atlantico', 1),
		('MANATI', 'Atlantico', 1),
		('PALMAR DE VARELA', 'Atlantico', 1),
		('PIOJO', 'Atlantico', 1),
		('POLONUEVO', 'Atlantico', 1),
		('PONEDERA', 'Atlantico', 1),
		('PUERTO COLOMBIA', 'Atlantico', 1),
		('REPELON', 'Atlantico', 1),
		('SABANAGRANDE', 'Atlantico', 1),
		('SABANALARGA', 'Atlantico', 1),
		('SANTA LUCIA', 'Atlantico', 1),
		('SANTO TOMAS', 'Atlantico', 1),
		('SOLEDAD', 'Atlantico', 1),
		('SUAN', 'Atlantico', 1),
		('TUBARA', 'Atlantico', 1),
		('USIACURI', 'Atlantico', 1),
		('ACHI', 'Bolivar', 1),
		('ARJONA', 'Bolivar', 1),
		('BARRANCO DE LOBA', 'Bolivar', 1),
		('CALAMAR', 'Bolivar', 1),
		('CARTAGENA', 'Bolivar', 1),
		('CORDOBA', 'Bolivar', 1),
		('EL CARMEN DE BOLIVAR', 'Bolivar', 1),
		('EL GUAMO', 'Bolivar', 1),
		('MAGANGUE', 'Bolivar', 1),
		('MAHATES', 'Bolivar', 1),
		('MARGARITA', 'Bolivar', 1),
		('MARIA LA BAJA', 'Bolivar', 1),
		('MOMPOS', 'Bolivar', 1),
		('MORALES', 'Bolivar', 1),
		('PINILLOS', 'Bolivar', 1),
		('RIO VIEJO', 'Bolivar', 1),
		('SAN ESTANISLAO', 'Bolivar', 1),
		('SAN FERNANDO', 'Bolivar', 1),
		('SAN JACINTO', 'Bolivar', 1),
		('SAN JUAN NEPOMUCENO', 'Bolivar', 1),
		('SAN MARTIN DE LOBA', 'Bolivar', 1),
		('SAN PABLO', 'Bolivar', 1),
		('SANTA CATALINA', 'Bolivar', 1),
		('SANTA ROSA', 'Bolivar', 1),
		('SANTA ROSA DEL SUR', 'Bolivar', 1),
		('SIMITI', 'Bolivar', 1),
		('SOPLAVIENTO', 'Bolivar', 1),
		('TALAIGUA NUEVO', 'Bolivar', 1),
		('TURBACO', 'Bolivar', 1),
		('TURBANA', 'Bolivar', 1),
		('VILLANUEVA', 'Bolivar', 1),
		('ZAMBRANO', 'Bolivar', 1),
		('ALMEIDA', 'Boyaca', 1),
		('AQUITANA', 'Boyaca', 1),
		('ARCABUCO', 'Boyaca', 1),
		('BELEN', 'Boyaca', 1),
		('BERBEO', 'Boyaca', 1),
		('BETEITIVA', 'Boyaca', 1),
		('BOAVITA', 'Boyaca', 1),
		('BOYACA', 'Boyaca', 1),
		('BRICEÑO', 'Boyaca', 1),
		('BUENAVISTA', 'Boyaca', 1),
		('BUSBANZA', 'Boyaca', 1),
		('CALDAS', 'Boyaca', 1),
		('CAMPOHERMOSO', 'Boyaca', 1),
		('CERINZA', 'Boyaca', 1),
		('CHINAVITA', 'Boyaca', 1),
		('CHIQUINQUIRA', 'Boyaca', 1),
		('CHIQUIZA', 'Boyaca', 1),
		('CHISCAS', 'Boyaca', 1),
		('CHITA', 'Boyaca', 1),
		('CHITARAQUE', 'Boyaca', 1),
		('CHIVATA', 'Boyaca', 1),
		('CHIVOR', 'Boyaca', 1),
		('CIENAGA', 'Boyaca', 1),
		('COMBITA', 'Boyaca', 1),
		('COPER', 'Boyaca', 1),
		('CORRALES', 'Boyaca', 1),
		('COVARACHIA', 'Boyaca', 1),
		('CUBARA', 'Boyaca', 1),
		('CUCAITA', 'Boyaca', 1),
		('CUITIVA', 'Boyaca', 1),
		('DUITAMA', 'Boyaca', 1),
		('EL COCUY', 'Boyaca', 1),
		('EL ESPINO', 'Boyaca', 1),
		('FIRAVITOVA', 'Boyaca', 1),
		('FLORESTA', 'Boyaca', 1),
		('GACHANTIVA', 'Boyaca', 1),
		('GAMEZA', 'Boyaca', 1),
		('GARAGOA', 'Boyaca', 1),
		('GUACAMAYAS', 'Boyaca', 1),
		('GUATEQUE', 'Boyaca', 1),
		('GUAYATA', 'Boyaca', 1),
		('GUICAN', 'Boyaca', 1),
		('IZA', 'Boyaca', 1),
		('JENESANO', 'Boyaca', 1),
		('JERICO', 'Boyaca', 1),
		('LA  VICTORIA', 'Boyaca', 1),
		('LA CAPILLA', 'Boyaca', 1),
		('LA UVITA', 'Boyaca', 1),
		('LABRANZAGRANDE', 'Boyaca', 1),
		('MACANAL', 'Boyaca', 1),
		('MARIPI', 'Boyaca', 1),
		('MIRAFLORES', 'Boyaca', 1),
		('MONGUA', 'Boyaca', 1),
		('MONGUI', 'Boyaca', 1),
		('MONIQUIRA', 'Boyaca', 1),
		('MOTAVITA', 'Boyaca', 1),
		('MUZO', 'Boyaca', 1),
		('NOBSA', 'Boyaca', 1),
		('NUEVO COLON', 'Boyaca', 1),
		('OICATA', 'Boyaca', 1),
		('OTANCHE', 'Boyaca', 1),
		('PACHAVITA', 'Boyaca', 1),
		('PAEZ', 'Boyaca', 1),
		('PAIPA', 'Boyaca', 1),
		('PAJANITO', 'Boyaca', 1),
		('PANQUEBA', 'Boyaca', 1),
		('PAUNA', 'Boyaca', 1),
		('PAYA', 'Boyaca', 1),
		('PAZ DEL RIO', 'Boyaca', 1),
		('PESCA', 'Boyaca', 1),
		('PISBA', 'Boyaca', 1),
		('PUERTO BOYACA', 'Boyaca', 1),
		('QUIPAMA', 'Boyaca', 1),
		('RAMIRIQUI', 'Boyaca', 1),
		('RAQUIRA', 'Boyaca', 1),
		('RONDON', 'Boyaca', 1),
		('SABOYA', 'Boyaca', 1),
		('SACHICA', 'Boyaca', 1),
		('SAMACA', 'Boyaca', 1),
		('SAN EDUARDO', 'Boyaca', 1),
		('SAN JOSE DE PARE', 'Boyaca', 1),
		('SAN LUIS DE GACENO', 'Boyaca', 1),
		('SAN MATEO', 'Boyaca', 1),
		('SAN MIGUEL DE SERNA', 'Boyaca', 1),
		('SAN PABLO DE BORBUR', 'Boyaca', 1),
		('SANTA MARIA', 'Boyaca', 1),
		('SANTA ROSA DE VITERBO', 'Boyaca', 1),
		('SANTA SOFIA', 'Boyaca', 1),
		('SANTANA', 'Boyaca', 1),
		('SATIVANORTE', 'Boyaca', 1),
		('SATIVASUR', 'Boyaca', 1),
		('SIACHOQUE', 'Boyaca', 1),
		('SOATA', 'Boyaca', 1),
		('SOCHA', 'Boyaca', 1),
		('SOCOTA', 'Boyaca', 1),
		('SOGAMOSO', 'Boyaca', 1),
		('SOMONDOCO', 'Boyaca', 1),
		('SORA', 'Boyaca', 1),
		('SORACA', 'Boyaca', 1),
		('SOTAQUIRA', 'Boyaca', 1),
		('SUSACON', 'Boyaca', 1),
		('SUTAMARCHAN', 'Boyaca', 1),
		('SUTATENZA', 'Boyaca', 1),
		('TASCO', 'Boyaca', 1),
		('TENZA', 'Boyaca', 1),
		('TIBANA', 'Boyaca', 1),
		('TIBASOSA', 'Boyaca', 1),
		('TINJACA', 'Boyaca', 1),
		('TIPACOQUE', 'Boyaca', 1),
		('TOCA', 'Boyaca', 1),
		('TOGUI', 'Boyaca', 1),
		('TOPAGA', 'Boyaca', 1),
		('TOTA', 'Boyaca', 1),
		('TUMEQUE', 'Boyaca', 1),
		('TUNJA', 'Boyaca', 1),
		('TUNUNGUA', 'Boyaca', 1),
		('TUTA', 'Boyaca', 1),
		('TUTASA', 'Boyaca', 1),
		('UMBITA', 'Boyaca', 1),
		('VENTAQUEMADA', 'Boyaca', 1),
		('VILLA DE LEYVA', 'Boyaca', 1),
		('VIRACACHA', 'Boyaca', 1),
		('ZETAQUIRA', 'Boyaca', 1),
		('AGUADAS', 'Caldas', 1),
		('ANSERMA', 'Caldas', 1),
		('ARANZAZU', 'Caldas', 1),
		('BELALCAZAR', 'Caldas', 1),
		('CHINCHINA', 'Caldas', 1),
		('FILADELFIA', 'Caldas', 1),
		('LA DORADA', 'Caldas', 1),
		('LA MERCED', 'Caldas', 1),
		('MANIZALES', 'Caldas', 1),
		('MANZANARES', 'Caldas', 1),
		('MARMATO', 'Caldas', 1),
		('MARQUETALIA', 'Caldas', 1),
		('MARULANDA', 'Caldas', 1),
		('NEIRA', 'Caldas', 1),
		('PACORA', 'Caldas', 1),
		('PALESTINA', 'Caldas', 1),
		('PENSILVANIA', 'Caldas', 1),
		('RIOSUCIO', 'Caldas', 1),
		('RISARALDA', 'Caldas', 1),
		('SALAMINA', 'Caldas', 1),
		('SAMANA', 'Caldas', 1),
		('SUPIA', 'Caldas', 1),
		('VICTORIA', 'Caldas', 1),
		('VILLAMARIA', 'Caldas', 1),
		('VITERBO', 'Caldas', 1),
		('ALBANIA', 'Caqueta', 1),
		('BELEN DE LOS ANDAQUIES', 'Caqueta', 1),
		('CARTAGENA DEL CHAIRA', 'Caqueta', 1),
		('CUNILLO', 'Caqueta', 1),
		('EL DONCELLO', 'Caqueta', 1),
		('EL PAUJIL', 'Caqueta', 1),
		('FLORENCIA', 'Caqueta', 1),
		('LA MONTAÑITA', 'Caqueta', 1),
		('MILAN', 'Caqueta', 1),
		('MORELIA', 'Caqueta', 1),
		('PUERTO RICO', 'Caqueta', 1),
		('SAN JOSE DE LA FRAGUA', 'Caqueta', 1),
		('SAN VICENTE DEL CAGUAN', 'Caqueta', 1),
		('SOLANO', 'Caqueta', 1),
		('SOLITA', 'Caqueta', 1),
		('VALPARAISO', 'Caqueta', 1),
		('AGUAZUL', 'Casanare', 1),
		('CHAMEZA', 'Casanare', 1),
		('HATO COROZAL', 'Casanare', 1),
		('LA SALINA', 'Casanare', 1),
		('MANI', 'Casanare', 1),
		('MONTERREY', 'Casanare', 1),
		('NUNCHIA', 'Casanare', 1),
		('OROCUE', 'Casanare', 1),
		('PAZ DE ARIPORO', 'Casanare', 1),
		('PORE', 'Casanare', 1),
		('RECETOR', 'Casanare', 1),
		('SABANALARGA', 'Casanare', 1),
		('SACAMA', 'Casanare', 1),
		('SAN LUIS DE PALENQUE', 'Casanare', 1),
		('TAMARA', 'Casanare', 1),
		('TAURAMENA', 'Casanare', 1),
		('TRINIDAD', 'Casanare', 1),
		('VILLANUEVA', 'Casanare', 1),
		('YOPAL', 'Casanare', 1),
		('ALMAGUER', 'Cauca', 1),
		('ARGELIA', 'Cauca', 1),
		('BALBOA', 'Cauca', 1),
		('BOLIVAR', 'Cauca', 1),
		('BUENOS AIRES', 'Cauca', 1),
		('CAJIBIO', 'Cauca', 1),
		('CALDONO', 'Cauca', 1),
		('CALOTO', 'Cauca', 1),
		('CORINTO', 'Cauca', 1),
		('EL TAMBO', 'Cauca', 1),
		('FLORENCIA', 'Cauca', 1),
		('GUAPI', 'Cauca', 1),
		('INZA', 'Cauca', 1),
		('JAMBALO', 'Cauca', 1),
		('LA SIERRA', 'Cauca', 1),
		('LA VEGA', 'Cauca', 1),
		('LOPEZ (MICAY)', 'Cauca', 1),
		('MERCADERES', 'Cauca', 1),
		('MIRANDA', 'Cauca', 1),
		('MORALES', 'Cauca', 1),
		('PADILLA', 'Cauca', 1),
		('PAEZ (BELALCAZAR)', 'Cauca', 1),
		('PATIA (EL BORDO)', 'Cauca', 1),
		('PIENDAMO', 'Cauca', 1),
		('POPAYAN', 'Cauca', 1),
		('PUERTO TEJADA', 'Cauca', 1),
		('PURACE', 'Cauca', 1),
		('ROSAS', 'Cauca', 1),
		('SAN SEBASTIAN', 'Cauca', 1),
		('SANTA ROSA', 'Cauca', 1),
		('SANTANDER DE QUILICHAO', 'Cauca', 1),
		('SILVIA', 'Cauca', 1),
		('SOTARA (PISPAMBA)', 'Cauca', 1),
		('SUAREZ', 'Cauca', 1),
		('TIMBIO', 'Cauca', 1),
		('TIMBIQUI', 'Cauca', 1),
		('TIRIBIO', 'Cauca', 1),
		('TOTORO', 'Cauca', 1),
		('AGUACHICA', 'Cesar', 1),
		('AGUSTIN CODAZZI', 'Cesar', 1),
		('ASTREA', 'Cesar', 1),
		('BECEMIL', 'Cesar', 1),
		('BOSCONIA', 'Cesar', 1),
		('CHIGUANA', 'Cesar', 1),
		('CHIMICHAGUA', 'Cesar', 1),
		('CURUMANI', 'Cesar', 1),
		('EL COPEY', 'Cesar', 1),
		('EL PASO', 'Cesar', 1),
		('GAMARRA', 'Cesar', 1),
		('GONZALES', 'Cesar', 1),
		('LA GLORIA', 'Cesar', 1),
		('LA JAGUA DE IBIRICO', 'Cesar', 1),
		('LA PAZ', 'Cesar', 1),
		('MANAURE (BALCON CESAR)', 'Cesar', 1),
		('PAILITAS', 'Cesar', 1),
		('PELAYA', 'Cesar', 1),
		('RIO DE ORO', 'Cesar', 1),
		('SAN ALBERTO', 'Cesar', 1),
		('SAN DIEGO', 'Cesar', 1),
		('SAN MARTIN', 'Cesar', 1),
		('TAMALAMEQUE', 'Cesar', 1),
		('VALLEDUPAR', 'Cesar', 1),
		('ACANDI', 'Choco', 1),
		('ALTO BAUDO', 'Choco', 1),
		('BAGADO', 'Choco', 1),
		('BAHIA SOLANO', 'Choco', 1),
		('BAJO BAUDO', 'Choco', 1),
		('BOJAYA', 'Choco', 1),
		('CONDOTO', 'Choco', 1),
		('EL CARMEN DE ATRATO', 'Choco', 1),
		('ISTMINA', 'Choco', 1),
		('JURADO', 'Choco', 1),
		('LITORAL DE SAN JUAN', 'Choco', 1),
		('LLORO', 'Choco', 1),
		('NOVITA', 'Choco', 1),
		('NUQUI', 'Choco', 1),
		('QUIBDO', 'Choco', 1),
		('RIOSUCIO', 'Choco', 1),
		('SAN JOSE DE PALMAR', 'Choco', 1),
		('SIPI', 'Choco', 1),
		('TADO', 'Choco', 1),
		('UNGUIA', 'Choco', 1),
		('AYAPEL', 'Cordova', 1),
		('BUENAVISTA', 'Cordova', 1),
		('CANALETE', 'Cordova', 1),
		('CERETE', 'Cordova', 1),
		('CHIMA', 'Cordova', 1),
		('CHINU', 'Cordova', 1),
		('CIENAGA DE ORO', 'Cordova', 1),
		('LORICA', 'Cordova', 1),
		('LOS CORDOBAS', 'Cordova', 1),
		('MOMIL', 'Cordova', 1),
		('MONTELIBANO', 'Cordova', 1),
		('MONTERIA', 'Cordova', 1),
		('MOÑITOS', 'Cordova', 1),
		('PLANETA RICA', 'Cordova', 1),
		('PUEBLO NUEVO', 'Cordova', 1),
		('PUERTO ESCONDIDO', 'Cordova', 1),
		('PUERTO LIBERTADOR', 'Cordova', 1),
		('PURISIMA', 'Cordova', 1),
		('SAHAGUN', 'Cordova', 1),
		('SAN ANDRES DE SOTAVENTO', 'Cordova', 1),
		('SAN ANTERO', 'Cordova', 1),
		('SAN BERNARDO DEL VIENTO', 'Cordova', 1),
		('SAN CARLOS', 'Cordova', 1),
		('SAN PELAYO', 'Cordova', 1),
		('TIERRALTA', 'Cordova', 1),
		('VALENCIA', 'Cordova', 1),
		('AGUA DE DIOS', 'Cundinamarca', 1),
		('ALBAN', 'Cundinamarca', 1),
		('ANAPOIMA', 'Cundinamarca', 1),
		('ANOLAIMA', 'Cundinamarca', 1),
		('APULO (RAFAEL REYES)', 'Cundinamarca', 1),
		('ARBELAEZ', 'Cundinamarca', 1),
		('BELTRAN', 'Cundinamarca', 1),
		('BITUIMA', 'Cundinamarca', 1),
		('BOJACA', 'Cundinamarca', 1),
		('CABRERA', 'Cundinamarca', 1),
		('CACHIPAY', 'Cundinamarca', 1),
		('CAJICA', 'Cundinamarca', 1),
		('CAPARRAPI', 'Cundinamarca', 1),
		('CAQUEZA', 'Cundinamarca', 1),
		('CARMEN DE CARUPA', 'Cundinamarca', 1),
		('CHAGUANI', 'Cundinamarca', 1),
		('CHIA', 'Cundinamarca', 1),
		('CHIPAQUE', 'Cundinamarca', 1),
		('CHOACHI', 'Cundinamarca', 1),
		('CHOCONTA', 'Cundinamarca', 1),
		('COGUA', 'Cundinamarca', 1),
		('COTA', 'Cundinamarca', 1),
		('CUCUNUBA', 'Cundinamarca', 1),
		('EL COLEGIO', 'Cundinamarca', 1),
		('EL PEÑON', 'Cundinamarca', 1),
		('FACACATIVA', 'Cundinamarca', 1),
		('FOMEQUE', 'Cundinamarca', 1),
		('FOSCA', 'Cundinamarca', 1),
		('FUNZA', 'Cundinamarca', 1),
		('FUQUENE', 'Cundinamarca', 1),
		('FUSAGASUGA', 'Cundinamarca', 1),
		('GACHALA', 'Cundinamarca', 1),
		('GACHANCIPA', 'Cundinamarca', 1),
		('GACHETA', 'Cundinamarca', 1),
		('GAMA', 'Cundinamarca', 1),
		('GIRARDOT', 'Cundinamarca', 1),
		('GUACHETA', 'Cundinamarca', 1),
		('GUADUAS', 'Cundinamarca', 1),
		('GUASCA', 'Cundinamarca', 1),
		('GUATAQUI', 'Cundinamarca', 1),
		('GUATAVITA', 'Cundinamarca', 1),
		('GUAYABAL DE SIQUIMA', 'Cundinamarca', 1),
		('GUAYABETAL', 'Cundinamarca', 1),
		('GUTIERREZ', 'Cundinamarca', 1),
		('JERUSALEN', 'Cundinamarca', 1),
		('JUNIN', 'Cundinamarca', 1),
		('LA CALERA', 'Cundinamarca', 1),
		('LA MESA', 'Cundinamarca', 1),
		('LA PALMA', 'Cundinamarca', 1),
		('LA PEÑA', 'Cundinamarca', 1),
		('LA VEGA', 'Cundinamarca', 1),
		('LENGUAZAQUE', 'Cundinamarca', 1),
		('MACHETA', 'Cundinamarca', 1),
		('MADRID', 'Cundinamarca', 1),
		('MANTA', 'Cundinamarca', 1),
		('MEDINA', 'Cundinamarca', 1),
		('MOSQUERA', 'Cundinamarca', 1),
		('NARIÑO', 'Cundinamarca', 1),
		('NEMOCON', 'Cundinamarca', 1),
		('NILO', 'Cundinamarca', 1),
		('NINAIMA', 'Cundinamarca', 1),
		('NOCAIMA', 'Cundinamarca', 1),
		('PACHO', 'Cundinamarca', 1),
		('PAIME', 'Cundinamarca', 1),
		('PANDI', 'Cundinamarca', 1),
		('PARATEBUENO', 'Cundinamarca', 1),
		('PASCA', 'Cundinamarca', 1),
		('PUERTO SALGAR', 'Cundinamarca', 1),
		('PULI', 'Cundinamarca', 1),
		('QUEBRADAGRANDE', 'Cundinamarca', 1),
		('QUETAME', 'Cundinamarca', 1),
		('QUIPILE', 'Cundinamarca', 1),
		('RICAURTE', 'Cundinamarca', 1),
		('SAN ANTONIO DEL TEQUENDAM', 'Cundinamarca', 1),
		('SAN BERNARDO', 'Cundinamarca', 1),
		('SAN CAYETANO', 'Cundinamarca', 1),
		('SAN FRANCISCO', 'Cundinamarca', 1),
		('SAN JUAN DE RIOSECO', 'Cundinamarca', 1),
		('BOGOTA D.C.', 'Cundinamarca', 1),
		('SASAIMA', 'Cundinamarca', 1),
		('SESQUILE', 'Cundinamarca', 1),
		('SIBATE', 'Cundinamarca', 1),
		('SILVANIA', 'Cundinamarca', 1),
		('SIMIJACA', 'Cundinamarca', 1),
		('SOACHA', 'Cundinamarca', 1),
		('SOPO', 'Cundinamarca', 1),
		('SUBACHOQUE', 'Cundinamarca', 1),
		('SUESCA', 'Cundinamarca', 1),
		('SUPATA', 'Cundinamarca', 1),
		('SUSA', 'Cundinamarca', 1),
		('SUTATAUSA', 'Cundinamarca', 1),
		('TABIO', 'Cundinamarca', 1),
		('TAUSA', 'Cundinamarca', 1),
		('TENA', 'Cundinamarca', 1),
		('TENJO', 'Cundinamarca', 1),
		('TIBACUY', 'Cundinamarca', 1),
		('TIBIRITA', 'Cundinamarca', 1),
		('TOCAIMA', 'Cundinamarca', 1),
		('TOCANCIPA', 'Cundinamarca', 1),
		('TOPAIPI', 'Cundinamarca', 1),
		('UBALA', 'Cundinamarca', 1),
		('UBAQUE', 'Cundinamarca', 1),
		('UBATE', 'Cundinamarca', 1),
		('UNE', 'Cundinamarca', 1),
		('UTICA', 'Cundinamarca', 1),
		('VENECIA', 'Cundinamarca', 1),
		('VERGARA', 'Cundinamarca', 1),
		('VIANI', 'Cundinamarca', 1),
		('VILLAGOMEZ', 'Cundinamarca', 1),
		('VILLAPINZON', 'Cundinamarca', 1),
		('VILLETA', 'Cundinamarca', 1),
		('VIOTA', 'Cundinamarca', 1),
		('YACOPI', 'Cundinamarca', 1),
		('ZIPACON', 'Cundinamarca', 1),
		('ZIPAQUIRA', 'Cundinamarca', 1),
		('GUAVIARE', 'Guainia', 1),
		('PUERTO INIRIDA', 'Guainia', 1),
		('CALAMAR', 'Guaviare', 1),
		('EL RETORNO', 'Guaviare', 1),
		('MIRAFLORES', 'Guaviare', 1),
		('SAN JOSE DEL GUAVIARE', 'Guaviare', 1),
		('ACEVEDO', 'Huila', 1),
		('AGRADO', 'Huila', 1),
		('AIPE', 'Huila', 1),
		('ALGECIRAS', 'Huila', 1),
		('ALTAMIRA', 'Huila', 1),
		('BARAYA', 'Huila', 1),
		('CAMPOALEGRE', 'Huila', 1),
		('COLOMBIA', 'Huila', 1),
		('ELIAS', 'Huila', 1),
		('GARZON', 'Huila', 1),
		('GIGANTE', 'Huila', 1),
		('GUADALUPE', 'Huila', 1),
		('HOBO', 'Huila', 1),
		('IQUIRA', 'Huila', 1),
		('ISNOS', 'Huila', 1),
		('LA ARGENTINA', 'Huila', 1),
		('LA PLATA', 'Huila', 1),
		('NATAGA', 'Huila', 1),
		('NEIVA', 'Huila', 1),
		('OPORAPA', 'Huila', 1),
		('PAICOL', 'Huila', 1),
		('PALERMO', 'Huila', 1),
		('PALESTINA', 'Huila', 1),
		('PITAL', 'Huila', 1),
		('PITALITO', 'Huila', 1),
		('RIVERA', 'Huila', 1),
		('SALADOBLANCO', 'Huila', 1),
		('SAN AGUSTIN', 'Huila', 1),
		('SANTA MARIA', 'Huila', 1),
		('SUAZA', 'Huila', 1),
		('TARQUI', 'Huila', 1),
		('TELLO', 'Huila', 1),
		('TENUEL', 'Huila', 1),
		('TESALIA', 'Huila', 1),
		('TIMANA', 'Huila', 1),
		('VILLAVIEJA', 'Huila', 1),
		('YAGUARA', 'Huila', 1),
		('BARRANCAS', 'La Guajira', 1),
		('EL MOLINO', 'La Guajira', 1),
		('FONSECA', 'La Guajira', 1),
		('MAICAO', 'La Guajira', 1),
		('MANAURE', 'La Guajira', 1),
		('RIOHACHA', 'La Guajira', 1),
		('SAN JUAN DEL CESAR', 'La Guajira', 1),
		('URIBIA', 'La Guajira', 1),
		('URUMITA', 'La Guajira', 1),
		('VILLANUEVA', 'La Guajira', 1),
		('ARACATACA', 'Magdalena', 1),
		('ARIGUANI', 'Magdalena', 1),
		('CERRO DE SAN ANTONIO', 'Magdalena', 1),
		('CHIVOLO', 'Magdalena', 1),
		('CIENAGA', 'Magdalena', 1),
		('EL BANCO', 'Magdalena', 1),
		('EL PIÑON', 'Magdalena', 1),
		('FUNDACION', 'Magdalena', 1),
		('GUAMAL', 'Magdalena', 1),
		('PIVIJAY', 'Magdalena', 1),
		('PLATO', 'Magdalena', 1),
		('PUEBLOVIEJO', 'Magdalena', 1),
		('REMOLINO', 'Magdalena', 1),
		('SAN SEBASTIAN DE BUENAVIS', 'Magdalena', 1),
		('SAN ZENON', 'Magdalena', 1),
		('SANTA ANA', 'Magdalena', 1),
		('SANTA MARTA', 'Magdalena', 1),
		('SITIONUEVO', 'Magdalena', 1),
		('TENERIFE', 'Magdalena', 1),
		('ACACIAS', 'Meta', 1),
		('BARRANCA DE UPIA', 'Meta', 1),
		('CABUYARO', 'Meta', 1),
		('CASTILLA LA NUEVA', 'Meta', 1),
		('CUBURRAL', 'Meta', 1),
		('CUMURAL', 'Meta', 1),
		('EL CALVARIO', 'Meta', 1),
		('EL CASTILLO', 'Meta', 1),
		('FUENTE DE ORO', 'Meta', 1),
		('GRANADA', 'Meta', 1),
		('GUAMAL', 'Meta', 1),
		('LA MACARENA', 'Meta', 1),
		('LA URIBE', 'Meta', 1),
		('LEJANIAS', 'Meta', 1),
		('MAPIRIPAN', 'Meta', 1),
		('MESETAS', 'Meta', 1),
		('PUERTO CONCORDIA', 'Meta', 1),
		('PUERTO GAITAN', 'Meta', 1),
		('PUERTO LLERAS', 'Meta', 1),
		('PUERTO LOPEZ', 'Meta', 1),
		('PUERTO RICO', 'Meta', 1),
		('RESTREPO', 'Meta', 1),
		('SAN CARLOS DE GARAGOA', 'Meta', 1),
		('SAN JUAN DE ARAMA', 'Meta', 1),
		('SAN JUANITO', 'Meta', 1),
		('SAN MARTIN', 'Meta', 1),
		('VILLAVICENCIO', 'Meta', 1),
		('VISTA HERMOSA', 'Meta', 1),
		('ALBAN', 'Nariño', 1),
		('ALDANA', 'Nariño', 1),
		('ANCUYA', 'Nariño', 1),
		('ARBOLEDA', 'Nariño', 1),
		('BARBACOAS', 'Nariño', 1),
		('BELEN', 'Nariño', 1),
		('BUESACO', 'Nariño', 1),
		('CHACHAGUI', 'Nariño', 1),
		('COLON', 'Nariño', 1),
		('CONSACA', 'Nariño', 1),
		('CONTADERO', 'Nariño', 1),
		('CORDOBA', 'Nariño', 1),
		('CUASPUD', 'Nariño', 1),
		('CUMBAL', 'Nariño', 1),
		('CUMBITARA', 'Nariño', 1),
		('EL CHARCO', 'Nariño', 1),
		('EL ROSARIO', 'Nariño', 1),
		('EL TABLON', 'Nariño', 1),
		('EL TAMBO', 'Nariño', 1),
		('FUNES', 'Nariño', 1),
		('GUACHUCAL', 'Nariño', 1),
		('GUAITANILLA', 'Nariño', 1),
		('GUALMATAN', 'Nariño', 1),
		('ILES', 'Nariño', 1),
		('IMUES', 'Nariño', 1),
		('IPIALES', 'Nariño', 1),
		('LA CRUZ', 'Nariño', 1),
		('LA FLORIDA', 'Nariño', 1),
		('LA LLANADA', 'Nariño', 1),
		('LA TOLA', 'Nariño', 1),
		('LA UNION', 'Nariño', 1),
		('LEIVA', 'Nariño', 1),
		('LINARES', 'Nariño', 1),
		('LOS ANDES', 'Nariño', 1),
		('MAGUI', 'Nariño', 1),
		('MALLAMA', 'Nariño', 1),
		('MOSQUERA', 'Nariño', 1),
		('OLAYA HERRERA', 'Nariño', 1),
		('OSPINA', 'Nariño', 1),
		('PASTO', 'Nariño', 1),
		('PIZARRO', 'Nariño', 1),
		('POLICARPA', 'Nariño', 1),
		('POTOSI', 'Nariño', 1),
		('PROVIDENCIA', 'Nariño', 1),
		('PUERRES', 'Nariño', 1),
		('PUPIALES', 'Nariño', 1),
		('RICAURTE', 'Nariño', 1),
		('ROBERTO PAYAN', 'Nariño', 1),
		('SAMANIEGO', 'Nariño', 1),
		('SAN BERNARDO', 'Nariño', 1),
		('SAN LORENZO', 'Nariño', 1),
		('SAN PABLO', 'Nariño', 1),
		('SAN PEDRO DE CARTAGO', 'Nariño', 1),
		('SANDONA', 'Nariño', 1),
		('SANTA BARBARA', 'Nariño', 1),
		('SANTACRUZ', 'Nariño', 1),
		('SAPUYES', 'Nariño', 1),
		('TAMINANGO', 'Nariño', 1),
		('TANGUA', 'Nariño', 1),
		('TUMACO', 'Nariño', 1),
		('TUQUEMES', 'Nariño', 1),
		('YACUANQUER', 'Nariño', 1),
		('ABREGO', 'Norte de Santander', 1),
		('ARBOLEDAS', 'Norte de Santander', 1),
		('BOCHALEMA', 'Norte de Santander', 1),
		('BUCARASICA', 'Norte de Santander', 1),
		('CACHIRA', 'Norte de Santander', 1),
		('CACOTA', 'Norte de Santander', 1),
		('CHINACOTA', 'Norte de Santander', 1),
		('CHITAGA', 'Norte de Santander', 1),
		('CONVENCION', 'Norte de Santander', 1),
		('CUCUTA', 'Norte de Santander', 1),
		('CUCUTILLA', 'Norte de Santander', 1),
		('DURANIA', 'Norte de Santander', 1),
		('EL CARMEN', 'Norte de Santander', 1),
		('EL TARRA', 'Norte de Santander', 1),
		('EL ZULIA', 'Norte de Santander', 1),
		('GRAMOLETE', 'Norte de Santander', 1),
		('HACARI', 'Norte de Santander', 1),
		('HERRAN', 'Norte de Santander', 1),
		('LA PLAYA', 'Norte de Santander', 1),
		('LABATECA', 'Norte de Santander', 1),
		('LOS PATIOS', 'Norte de Santander', 1),
		('LOURDES', 'Norte de Santander', 1),
		('MUTISCUA', 'Norte de Santander', 1),
		('OCAÑA', 'Norte de Santander', 1),
		('PAMPLONA', 'Norte de Santander', 1),
		('RAGONVALIA', 'Norte de Santander', 1),
		('SALAZAR', 'Norte de Santander', 1),
		('SAN CALIXTO', 'Norte de Santander', 1),
		('SAN CAYETANO', 'Norte de Santander', 1),
		('SANTIAGO', 'Norte de Santander', 1),
		('SARDINATA', 'Norte de Santander', 1),
		('SILOS', 'Norte de Santander', 1),
		('TEORAMA', 'Norte de Santander', 1),
		('TIBU', 'Norte de Santander', 1),
		('TOLEDO', 'Norte de Santander', 1),
		('VILLA CARO', 'Norte de Santander', 1),
		('VILLA ROSARIO', 'Norte de Santander', 1),
		('COLON', 'Putumayo', 1),
		('MOCOA', 'Putumayo', 1),
		('ORITO', 'Putumayo', 1),
		('PUERTO ASIS', 'Putumayo', 1),
		('PUERTO CAICEDO', 'Putumayo', 1),
		('PUERTO GUZMAN', 'Putumayo', 1),
		('PUERTO LEGUIZAMO', 'Putumayo', 1),
		('SAN FRANCISCO', 'Putumayo', 1),
		('SANTIAGO', 'Putumayo', 1),
		('SIBUNDOY', 'Putumayo', 1),
		('VALLE DE GUAMEZ', 'Putumayo', 1),
		('VILLAGARZON', 'Putumayo', 1),
		('ARMENIA', 'Quindio', 1),
		('BUENAVISTA', 'Quindio', 1),
		('CALARCA', 'Quindio', 1),
		('CIRCASIA', 'Quindio', 1),
		('CORDOBA', 'Quindio', 1),
		('FINLANDIA', 'Quindio', 1),
		('GENOVA', 'Quindio', 1),
		('LA TEBAIDA', 'Quindio', 1),
		('MONTENEGRO', 'Quindio', 1),
		('PIJAO', 'Quindio', 1),
		('QUIMBAYA', 'Quindio', 1),
		('SALENTO', 'Quindio', 1),
		('APIA', 'Risaralda', 1),
		('BALBOA', 'Risaralda', 1),
		('BELEN DE UMBRIA', 'Risaralda', 1),
		('DOSQUEBRADAS', 'Risaralda', 1),
		('GUATICA', 'Risaralda', 1),
		('LA CELIA', 'Risaralda', 1),
		('LA VIRGINIA', 'Risaralda', 1),
		('MARSELLA', 'Risaralda', 1),
		('MISTRATO', 'Risaralda', 1),
		('PEREIRA', 'Risaralda', 1),
		('PUEBLO RICO', 'Risaralda', 1),
		('QUINCHIA', 'Risaralda', 1),
		('SANTA ROSA DE CABAL', 'Risaralda', 1),
		('SANTUARIO', 'Risaralda', 1),
		('AGUADA', 'Santander', 1),
		('ALBANIA', 'Santander', 1),
		('AROTACA', 'Santander', 1),
		('BARBOSA', 'Santander', 1),
		('BARICHARA', 'Santander', 1),
		('BARRANCABERMEJA', 'Santander', 1),
		('BETULIA', 'Santander', 1),
		('BOLIVAR', 'Santander', 1),
		('BUCARAMANGA', 'Santander', 1),
		('CABRERA', 'Santander', 1),
		('CALIFORNIA', 'Santander', 1),
		('CAPITANEJO', 'Santander', 1),
		('CARCASI', 'Santander', 1),
		('CEPITA', 'Santander', 1),
		('CERRITO', 'Santander', 1),
		('CHARALA', 'Santander', 1),
		('CHARTA', 'Santander', 1),
		('CHIMA', 'Santander', 1),
		('CHIPATA', 'Santander', 1),
		('CIMITARRA', 'Santander', 1),
		('CONCEPCION', 'Santander', 1),
		('CONFINES', 'Santander', 1),
		('CONTRATACION', 'Santander', 1),
		('COROMORO', 'Santander', 1),
		('CURUTI', 'Santander', 1),
		('EL CARMEN DE CHUCURI', 'Santander', 1),
		('EL GUACAMAYO', 'Santander', 1),
		('EL PEÑON', 'Santander', 1),
		('EL PLAYON', 'Santander', 1),
		('ENCINO', 'Santander', 1),
		('ENCISO', 'Santander', 1),
		('FLORIAN', 'Santander', 1),
		('FLORIDABLANCA', 'Santander', 1),
		('GALAN', 'Santander', 1),
		('GAMBITA', 'Santander', 1),
		('GIRON', 'Santander', 1),
		('GUACA', 'Santander', 1),
		('GUADALUPE', 'Santander', 1),
		('GUAPOTA', 'Santander', 1),
		('GUAVATA', 'Santander', 1),
		('GUEPSA', 'Santander', 1),
		('HATO', 'Santander', 1),
		('JESUS MARIA', 'Santander', 1),
		('JORDAN', 'Santander', 1),
		('LA BELLEZA', 'Santander', 1),
		('LA PAZ', 'Santander', 1),
		('LANDAZURI', 'Santander', 1),
		('LEBRIJA', 'Santander', 1),
		('LOS SANTOS', 'Santander', 1),
		('MACARAVITA', 'Santander', 1),
		('MALAGA', 'Santander', 1),
		('MATANZA', 'Santander', 1),
		('MOGOLES', 'Santander', 1),
		('MOLOGAVITA', 'Santander', 1),
		('OCAMONTE', 'Santander', 1),
		('OIBA', 'Santander', 1),
		('ONZAGA', 'Santander', 1),
		('PALMAR', 'Santander', 1),
		('PALMSA DEL SOCORRO', 'Santander', 1),
		('PARAMO', 'Santander', 1),
		('PIEDECUESTA', 'Santander', 1),
		('PINCHOTE', 'Santander', 1),
		('PUENTE NACIONAL', 'Santander', 1),
		('PUERTO PARRA', 'Santander', 1),
		('PUERTO WILCHES', 'Santander', 1),
		('RIONEGRO', 'Santander', 1),
		('SABANA DE TORRES', 'Santander', 1),
		('SAN ANDRES', 'Santander', 1),
		('SAN BENITO', 'Santander', 1),
		('SAN GIL', 'Santander', 1),
		('SAN JOAQUIN', 'Santander', 1),
		('SAN JOSE DE MIRANDA', 'Santander', 1),
		('SAN MIGUEL', 'Santander', 1),
		('SAN VICENTE DE CHUCURI', 'Santander', 1),
		('SANTA BARBARA', 'Santander', 1),
		('SANTA HELENA DEL OPON', 'Santander', 1),
		('SIMACOTA', 'Santander', 1),
		('SOCORRO', 'Santander', 1),
		('SUAITA', 'Santander', 1),
		('SUCRE', 'Santander', 1),
		('SURATA', 'Santander', 1),
		('TONA', 'Santander', 1),
		('VALLE DE SAN JOSE', 'Santander', 1),
		('VELEZ', 'Santander', 1),
		('VETAS', 'Santander', 1),
		('VILLANUEVA', 'Santander', 1),
		('ZAPATOCA', 'Santander', 1),
		('BUENAVISTA', 'Sucre', 1),
		('CAIMITO', 'Sucre', 1),
		('CHALAN', 'Sucre', 1),
		('COLOSO', 'Sucre', 1),
		('COROZAL', 'Sucre', 1),
		('GALERAS', 'Sucre', 1),
		('GUARANDA', 'Sucre', 1),
		('LA UNION DE SUCRE', 'Sucre', 1),
		('LOS PALMITOS', 'Sucre', 1),
		('MAJAGUAL', 'Sucre', 1),
		('MORROA', 'Sucre', 1),
		('OVEJAS', 'Sucre', 1),
		('PALMITO', 'Sucre', 1),
		('SAMPUES', 'Sucre', 1),
		('SAN BENITO ABAD', 'Sucre', 1),
		('SAN JUAN DE BETULIA', 'Sucre', 1),
		('SAN MARCOS', 'Sucre', 1),
		('SAN ONOFRE', 'Sucre', 1),
		('SAN PEDRO', 'Sucre', 1),
		('SINCELEJO', 'Sucre', 1),
		('SUCRE', 'Sucre', 1),
		('TOLU', 'Sucre', 1),
		('TOLUVIEJO', 'Sucre', 1),
		('ALPUJARRA', 'Tolima', 1),
		('ALVARADO', 'Tolima', 1),
		('AMBALEMA', 'Tolima', 1),
		('ANZOATEGUI', 'Tolima', 1),
		('ARMERO', 'Tolima', 1),
		('ATACO', 'Tolima', 1),
		('CAJAMARCA', 'Tolima', 1),
		('CARMEN DE APICALA', 'Tolima', 1),
		('CASABLANCA', 'Tolima', 1),
		('CHAPARRAL', 'Tolima', 1),
		('COELLO', 'Tolima', 1),
		('COYAIMA', 'Tolima', 1),
		('CUNDAY', 'Tolima', 1),
		('DOLORES', 'Tolima', 1),
		('ESPINAL', 'Tolima', 1),
		('FALAN', 'Tolima', 1),
		('FLANDES', 'Tolima', 1),
		('FRESNO', 'Tolima', 1),
		('GUAMO', 'Tolima', 1),
		('HERVEO', 'Tolima', 1),
		('HONDA', 'Tolima', 1),
		('IBAGUE', 'Tolima', 1),
		('ICONONZO', 'Tolima', 1),
		('LERIDA', 'Tolima', 1),
		('LIBANO', 'Tolima', 1),
		('MARIQUITA', 'Tolima', 1),
		('MELGAR', 'Tolima', 1),
		('MURILLO', 'Tolima', 1),
		('NATAGAIMA', 'Tolima', 1),
		('ORTEGA', 'Tolima', 1),
		('PIEDRAS', 'Tolima', 1),
		('PLANADAS', 'Tolima', 1),
		('PRADO', 'Tolima', 1),
		('PURIFICACION', 'Tolima', 1),
		('RIOBLANCO', 'Tolima', 1),
		('RONCESVALLES', 'Tolima', 1),
		('ROVIRA', 'Tolima', 1),
		('SALDAÑA', 'Tolima', 1),
		('SAN ANTONIO', 'Tolima', 1),
		('SAN LUIS', 'Tolima', 1),
		('SANTA ISABEL', 'Tolima', 1),
		('SUAREZ', 'Tolima', 1),
		('VALLE DE SAN JUAN', 'Tolima', 1),
		('VENADILLO', 'Tolima', 1),
		('VILLAHERMOSA', 'Tolima', 1),
		('VILLARRICA', 'Tolima', 1),
		('ALCALA', 'Valle del Cauca', 1),
		('ANDALUCIA', 'Valle del Cauca', 1),
		('ANSERMANUEVO', 'Valle del Cauca', 1),
		('ARGELIA', 'Valle del Cauca', 1),
		('BOLIVAR', 'Valle del Cauca', 1),
		('BUENAVENTURA', 'Valle del Cauca', 1),
		('BUGA', 'Valle del Cauca', 1),
		('BUGALAGRANDE', 'Valle del Cauca', 1),
		('CAICEDONIA', 'Valle del Cauca', 1);

INSERT INTO ciudad
	(nombre, region, idpais)
	VALUES('CALI', 'Valle del Cauca', 1),
	('CALIMA', 'Valle del Cauca', 1),
	('CANDELARIA', 'Valle del Cauca', 1),
	('CARTAGO', 'Valle del Cauca', 1),
	('DAGUA', 'Valle del Cauca', 1),
	('EL AGUILA', 'Valle del Cauca', 1),
	('EL CAIRO', 'Valle del Cauca', 1),
	('EL CERRITO', 'Valle del Cauca', 1),
	('EL DOVIO', 'Valle del Cauca', 1),
	('FLORIDA', 'Valle del Cauca', 1),
	('GINEBRA', 'Valle del Cauca', 1),
	('GUACARI', 'Valle del Cauca', 1),
	('JAMUNDI', 'Valle del Cauca', 1),
	('LA CUMBRE', 'Valle del Cauca', 1),
	('LA UNION', 'Valle del Cauca', 1),
	('LA VICTORIA', 'Valle del Cauca', 1),
	('OBANDO', 'Valle del Cauca', 1),
	('PALMIRA', 'Valle del Cauca', 1),
	('PRADERA', 'Valle del Cauca', 1),
	('RESTREPO', 'Valle del Cauca', 1),
	('RIOFRIO', 'Valle del Cauca', 1),
	('ROLDANILLO', 'Valle del Cauca', 1),
	('SAN PEDRO', 'Valle del Cauca', 1),
	('SEVILLA', 'Valle del Cauca', 1),
	('TORO', 'Valle del Cauca', 1),
	('TRUJILLO', 'Valle del Cauca', 1),
	('TULUA', 'Valle del Cauca', 1),
	('ULLOA', 'Valle del Cauca', 1),
	('VERSALLES', 'Valle del Cauca', 1),
	('VIJES', 'Valle del Cauca', 1),
	('YOTOCO', 'Valle del Cauca', 1),
	('YUMBO', 'Valle del Cauca', 1),
	('ZARZAL', 'Valle del Cauca', 1),
	('CARURU', 'Vaupes', 1),
	('MITU', 'Vaupes', 1),
	('PACOA', 'Vaupes', 1),
	('YARAVATE', 'Vaupes', 1),
	('LA PRIMAVERA', 'Vichada', 1),
	('NUEVA ANTIOQUIA', 'Vichada', 1),
	('PUERTO CARREÑO', 'Vichada', 1),
	('SAN JOSE DE OCUNE', 'Vichada', 1),
	('SANTA RITA', 'Vichada', 1),
	('SANTA ROSALIA', 'Vichada', 1);

INSERT INTO nivelacademico
	(id, nivel)
	VALUES (1, 'Básico'),
		(2, 'Pregrado'),
		(3, 'Postgrado'),
		(4, 'Formación Continua');

INSERT INTO gradoacademico
	(grado, idnivel)
	VALUES('Primaria', 1),
		('Bachillerato Académico', 1),
		('Bachillerato Técnico', 1),
		('Tecnología', 2),
		('Profesional', 2),
		('Licenciatura', 2),
		('Especialización', 3),
		('Maestría', 3),
		('Doctorado', 3),
		('Diplomado', 4),
		('Curso', 4);
		
INSERT INTO sector
	(sector)
	VALUES ('Tecnología'),
		('Finanzas'),
		('Salud'),
		('Logística');

INSERT INTO idioma
	(idioma)
	VALUES ('Español'),
		('Inglés'),
		('Portugués'),
		('Francés'),
		('Emberá');

